### ISSUE TITLE
data-bs

### ISSUE THREAD

**Issue by laoshaw** [themeselection/bootstrap-cheatsheet#1]
a major change is data-bs- instead of data- that probably should be added to the cheat sheet

**Comment by ajaypatelaj** [comment]
Hi @laoshaw 

Correct we will make it correct in our next release 🚀

**Comment by monab** [comment]
Hi @laoshaw,
All the components are updated with "data-bs-" instead of "data-". Let me know, if you found this anywhere in our cheatsheet, so we can update it as well :)
Regards~

**Comment by laoshaw** [comment]
Looks great. Thanks!
